refactor IDTransform to use variant type
reyoung/torchrec pull request #24
Opened 2022-07-28 08:37 UTC by zhuzilin

2022-07-28 10:12 UTC, reyoung requested changes

2022-07-28 10:12 UTC, reyoung commented on contrib/dynamic_embedding/src/tde/bind.cpp
> +      .def("transform", &IDTransformer::Transform)
Transform直接返回IDToFetch吧？

或者，作为transform的一个out参数也行？

2022-07-28 10:12 UTC, reyoung commented on contrib/dynamic_embedding/src/torchrec_dynamic_embedding/__init__.py
> +        if "id_transformer" not in kwargs:
感觉这个参数名略怪。
```
IDTransformer(id_transformer={...})
```

不如叫

```
IDTransformer(eviction_config={}, transform_config={})
```

2022-07-28 12:07 UTC, zhuzilin commented on contrib/dynamic_embedding/src/tde/bind.cpp
> +      .def("transform", &IDTransformer::Transform)
fixed. 改成了返回 2 个值，保留之前的 num_transformed 因为感觉这样比较容易判断啥时候该 evict 了

2022-07-28 12:07 UTC, zhuzilin commented on contrib/dynamic_embedding/src/torchrec_dynamic_embedding/__init__.py
> +        if "id_transformer" not in kwargs:
fixed.

2022-07-29 03:02 UTC, reyoung approved these changes

2022-07-29 03:02 UTC, merged