Implement NaiveIDTransformer
reyoung/torchrec pull request #9
Opened 2022-07-25 09:30 UTC by zhuzilin

2022-07-25 12:15 UTC, zhuzilin commented
```
--------------------------------------------------------------------------------------------
Benchmark                                                  Time             CPU   Iterations
--------------------------------------------------------------------------------------------
BM_MultiThreadedIDTransformer_Cold/iterations:100        108 ms          108 ms          100
BM_MultiThreadedIDTransformer_Hot/iterations:100        23.3 ms         23.3 ms          100
```

2022-07-25 12:20 UTC, zhuzilin commented
一些可能需要讨论的地方：
- 我把 `ExtendValue` 重命名为 `Tag` 了，因为感觉 `ExtendValue` 太长了，和 `Tag` 一样都没有啥特殊的含义。另外就是重命名了一点 template 参数；
- 目前是用 bitmask 做的 eviction，没想好这部分怎么做 benchmark。

2022-07-26 04:12 UTC, reyoung requested changes
有一些细节需要修改

2022-07-26 04:12 UTC, reyoung commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer.h
> +      const int64_t num_embedding,
去掉const。

参数传递只有以下几种类型:
* T
* const T&
* T&&
* T*

2022-07-26 04:12 UTC, reyoung commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer.h
> +      Update update = [](Tag tag, int64_t global_id, int64_t cache_id) -> Tag {
这里不然还是给个Optional<Tag>？不然外部很难判断这个tag是不是有值

2022-07-26 04:12 UTC, reyoung commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer.h
> +  ska::flat_hash_map<int64_t, int64_t> global_id2cache_id_;
其实，Tag是不是可以直接是这个ValueType？

2022-07-26 04:12 UTC, reyoung commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer_impl.h
> +    const int64_t global_id = global_ids[i];
其实没太有必要用const😂，虽然其实也无所谓。

2022-07-26 04:12 UTC, reyoung commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer_impl.h
> +    if (filter(global_id)) {
```cpp
if (!filter(...)) {
  continue
}
```

可以让锁进窄一点

2022-07-26 04:12 UTC, reyoung commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer_impl.h
> +        if (bitmasks_.full_)
bitmasks_.full() 吧。

另外单行的if也要有大括号

2022-07-26 04:12 UTC, reyoung commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer_impl.h
> +      cache_ids[i] = cache_id + embedding_offset_;
embedding_offset_ 这个其实有点难受。感觉不是这个类型应该做的事情，放到了这个类型里。。

回头我再想想咋做合适吧。

2022-07-26 04:12 UTC, reyoung commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer_impl.h
> +  for (auto& pair : global_id2cache_id_) {
for (auto [global_id, cache_id] : global_id2cache_id_)

2022-07-26 04:12 UTC, reyoung commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer_impl.h
> +  bitmasks_[bitmask_offset] |= 1 << bit_offset;
哦，看到了在Transformer::Evict里的调用。

不过还是直接在FreeBit里把 next_free_bit_ 调整正确吧。

这个函数不应该依赖使用方怎么使用，来确定他是不是正确。

2022-07-26 04:12 UTC, reyoung commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer.h
> +  bool full_;
其实，我不是很理解这个bool的作用，其实就是next_free_bit_ 是不是小于某个值，来表示这个masks是不是free就好了。

2022-07-26 04:12 UTC, reyoung commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer_impl.h
> +    if (iter != global_id2cache_id_.end()) {
同理

```
if (it == end() ) {
  continue;
}
```

2022-07-26 04:12 UTC, reyoung commented on .pre-commit-config.yaml
> +  - repo: https://github.com/pre-commit/mirrors-clang-format
这个还是别改了。

或者最后merge回torchrec的时候再改回去。

2022-07-26 06:05 UTC, zhuzilin commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer.h
> +      Update update = [](Tag tag, int64_t global_id, int64_t cache_id) -> Tag {
嗯...这里我觉得现在设计比较矛盾的一个点... `Tag` 应该来源于具体的 strategy，所以只有 strategy 自己知道一个 tag 是不是空的，而 id transformer 里面是不知道的... 所以这个 `update` 函数还是只能由同一个 strategy 提供... 或者也许我们可以把 strategy 作为 transformer 类的模板类？但是那样又不太好做测试了...

2022-07-26 06:06 UTC, zhuzilin commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer.h
> +  ska::flat_hash_map<int64_t, int64_t> global_id2cache_id_;
也可以，不过我想的是这里的 `Tag` 就是 strategy 里的 record 了，而 strategy 里面应该是不需要 cache id 的

2022-07-26 06:08 UTC, zhuzilin commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer_impl.h
> +BitMaskGroup<BitMask>::BitMaskGroup(int64_t total_bits)
没有 specify 的模板韩式是不是不用 inline?

2022-07-26 06:25 UTC, zhuzilin commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer_impl.h
> +  bitmasks_[bitmask_offset] = bitmask & (bitmask - 1);
对，现在设计的是 1 是这一位是空的，0 是这一位已经被占了。

`mask & (1 << offset)` 相当于把除了 `offset` 这位以外都设为 0 了，而 `bitmask & (bitmask - 1)` 会把一个二进制数的最后一个 1 改为 0，不会影响前面的位。

2022-07-26 06:37 UTC, zhuzilin commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer_impl.h
> +    next_free_bit_ = bitmask_offset * B + __builtin_ctz(bitmask);
嗯，我暂时先用 `if constexpr` 糊一下...感觉这部分我们可以在 util 里面包一下，因为 lxu 那里也在用

2022-07-26 06:54 UTC, zhuzilin commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer.h
> +      const int64_t num_embedding,
学到了~

2022-07-26 06:57 UTC, reyoung commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer.h
> +      Update update = [](Tag tag, int64_t global_id, int64_t cache_id) -> Tag {
IDTransformer本身是一个映射，如果这个global id是第一次出现，给update函数的tag就传 nullopt即可

2022-07-26 06:58 UTC, reyoung commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer.h
> +  ska::flat_hash_map<int64_t, int64_t> global_id2cache_id_;
是的。所以global_id_to_cache_id_的类型大约是

```cpp
struct CacheValue {
  int64_t cache_id_;
  Tag tag_;
};
```

2022-07-26 07:39 UTC, reyoung commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer.h
> +  Bitmap(int64_t num_bits);
```cpp
explicit Bitmap(int64_t num_bits);
```

2022-07-26 08:22 UTC, zhuzilin commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer.h
> +  Bitmap(int64_t num_bits);
这里是刚刚改漏了... fixed...

2022-07-26 08:24 UTC, zhuzilin commented on contrib/dynamic_embedding/src/tde/details/naive_id_transformer.h
> +  ska::flat_hash_map<int64_t, int64_t> global_id2cache_id_;
这里改过来之后会稍微慢一点点，可能是因为把分配内存移到插入里面去了，不过理论上合起来应该更符合 locality，所以还是改过来了。然后更新后的 benchmark 是：
```
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations
------------------------------------------------------------------------------------
BM_NaiveIDTransformer_Cold/iterations:100        124 ms          124 ms          100
BM_NaiveIDTransformer_Hot/iterations:100        27.3 ms         27.3 ms          100
```

2022-07-26 09:49 UTC, reyoung approved these changes

2022-07-26 09:53 UTC, merged